spring.application.name=taskservice
server.port=8082

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://192.168.88.205:5432/task_service
spring.datasource.username=javajabka
spring.datasource.password=${DB_PG_PWD}

spring.rabbitmq.addresses=192.168.88.30:5672
spring.rabbitmq.username=javajabka
spring.rabbitmq.password=${RABBITMQ_PWD}
spring.rabbitmq.virtual-host=event

app.rabbitmq.queue=event_queue
app.rabbitmq.exchange=event_exchange

url.service.user=http://localhost:8081/